behaviors:
  CollabAgent:
    trainer_type: poca  # POCA kullan!

    init_path: C:\Users\Batuhan\Documents\GitHub\Unity-ML-3D\Ml-3D\Assets\Projects\PushBlock\Configs\results\Run2\CollabAgent\CollabAgent-6000444.pt

    hyperparameters:
      batch_size: 512
      buffer_size: 40960
      learning_rate: 3e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 5
      learning_rate_schedule: linear

    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 6.0e6
    time_horizon: 256
    summary_freq: 10000
